version: '2'
services:
    deluge:
        image: radmen/deluge-seed:deluge
        volumes:
            - data:/deluge/completed
    web:
        image: radmen/deluge-seed:web
        ports:
            - 443:443
        volumes:
            - data:/deluge/completed
volumes:
    data:
